obj-y += dma_alloc.o
obj-y += fontLib_16x32B.o
obj-y += fontLib_16x32.o
obj-y += fontLib_8x16.o
obj-y += graphics_Draw.o
obj-y += rv1106_gpio.o
obj-y += rv1106_isp.o
obj-y += rv1106_rgn.o
obj-y += rv1106_venc.o
obj-y += rv1106_vi.o
obj-y += rv1106_video_init.o
obj-y += rv1106_vpss.o

obj-$(CONFIG_ENABLE_ROCKCHIP_IVA) += rv1106_iva.o

ifdef CONFIG_ENABLE_SCREEN_PANEL
obj-y += screen_panel_driver.o
obj-y += rgb_lcd.o
endif
