#!/bin/sh
cmd=`realpath $0`
_DIR=`dirname $cmd`

. /configs/function_set

case $1 in
    start)
        [ "${RUN_RTSP_PUSH}" = "1" ] && /oem/bin/10_rtsp_push &
        ;;
    stop)
        sync
        ;;
    *)
        exit 1
        ;;
esac
