#!/bin/sh
cmd=`realpath $0`
_DIR=`dirname $cmd`

. /configs/function_set

case $1 in
    start)
        [ "${RUN_IPC_PROCESS}" = "1" ] && /oem/bin/00_myipc &
        ;;
    stop)
        sync
        ;;
    *)
        exit 1
        ;;
esac
